# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'PresentTableViewModelDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PresentTableViewModel
  #pod 'PresentTableViewModel', :path => '../'
  pod 'PresentTableViewModel', :git => 'https://github.com/presentco/PresentTableViewModel.git'

  pod 'Then'
  pod 'TinyConstraints'

end
